// Typed SBR API client. Types come from ./schema (generated by `pnpm generate:api` from the
// backend OpenAPI schema), so request paths, params, and responses are checked against the API.
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";

import type { paths } from "./schema";

// Default to the same-origin "/api" proxy (next.config rewrites it to the backend), so the browser
// never makes a cross-origin request and CORS is a non-issue. Override with NEXT_PUBLIC_API_BASE_URL
// to point the client straight at a CORS-enabled backend instead.
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "/api";

export const fetchClient = createFetchClient<paths>({ baseUrl: API_BASE_URL });

// $api exposes TanStack Query hooks ($api.useQuery / useMutation) bound to the typed paths.
export const $api = createClient(fetchClient);
