// Typed SBR API client. Types come from ./schema (generated by `pnpm generate:api` from the
// backend OpenAPI schema), so request paths, params, and responses are checked against the API.
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";

import type { paths } from "./schema";

// The backend base URL. Defaults to the local FastAPI dev server; set NEXT_PUBLIC_API_BASE_URL
// (see .env.example) for deployed environments.
export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

export const fetchClient = createFetchClient<paths>({ baseUrl: API_BASE_URL });

// $api exposes TanStack Query hooks ($api.useQuery / useMutation) bound to the typed paths.
export const $api = createClient(fetchClient);
