/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services/supportedAlgorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported Algorithms */
        get: operations["supported_algorithms_services_supportedAlgorithms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Trusted generation-side ingest (authenticated in prod). Public surface is /matches/*.
         *
         *     The asset hash is computed from the uploaded bytes, never taken from the client, and an existing
         *     manifest id is not overwritten.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/byContent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matches By Content */
        post: operations["matches_by_content_matches_byContent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/byBinding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches By Binding */
        get: operations["matches_by_binding_matches_byBinding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transparency/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transparency Log
         * @description The append-ordered log leaves plus the current root. A transparency log is meant to be
         *     auditable, so the entries are public; this also feeds the Merkle explorer.
         */
        get: operations["transparency_log_transparency_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transparency/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transparency Checkpoint
         * @description The current signed tree head. Idempotent: the epoch is the tree size, so re-reading an
         *     unchanged tree returns the same signed checkpoint. The public key travels with it.
         */
        get: operations["transparency_checkpoint_transparency_checkpoint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transparency/proof/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transparency Proof
         * @description An inclusion proof for a manifest, pinned to a signed checkpoint so the client can bind the
         *     leaf to a signed tree head without trusting this endpoint.
         */
        get: operations["transparency_proof_transparency_proof__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns no provenance data, safe for an unauthenticated check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlgorithmEntry
         * @description One advertised soft-binding algorithm (the C2PA SBR softBindingAlgList entry shape).
         */
        AlgorithmEntry: {
            /** Alg */
            alg: string;
        };
        /** Body_ingest_ingest_post */
        Body_ingest_ingest_post: {
            /** File */
            file: string;
            /** Manifest Id */
            manifest_id: string;
            /** Watermark Id */
            watermark_id: string;
            /**
             * Model
             * @default unknown
             */
            model: string;
        };
        /** Body_matches_by_content_matches_byContent_post */
        Body_matches_by_content_matches_byContent_post: {
            /** File */
            file: string;
        };
        /**
         * CheckpointResponse
         * @description A signed Merkle tree head plus the public key to verify it independently.
         *
         *     key_source is "configured" for a real loaded key or "ephemeral" for a dev/CI key, so a client
         *     never mistakes a throwaway key for a trust anchor.
         */
        CheckpointResponse: {
            checkpoint: components["schemas"]["MerkleCheckpoint"];
            /** Publickeyhex */
            publicKeyHex: string;
            /** Keysource */
            keySource: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InclusionProofResponse
         * @description A self-contained, independently-verifiable inclusion proof.
         *
         *     The client resolves the serialized proof to a root and confirms that root equals the embedded
         *     signed checkpoint's root_hash, then verifies the checkpoint signature against public_key_hex.
         *     server_verified is only the server's own check and is not a substitute for that client-side
         *     verification. leaf_hash is the manifest's canonical hash (the leaf), unchanged by redaction.
         */
        InclusionProofResponse: {
            /** Manifestid */
            manifestId: string;
            /** Leafindex */
            leafIndex: number;
            /** Leafhash */
            leafHash: string;
            /** Treesize */
            treeSize: number;
            /** Roothash */
            rootHash: string;
            /** Proof */
            proof: {
                [key: string]: unknown;
            };
            checkpoint: components["schemas"]["MerkleCheckpoint"];
            /** Publickeyhex */
            publicKeyHex: string;
            /** Keysource */
            keySource: string;
            /** Serververified */
            serverVerified: boolean;
        };
        /**
         * LogEntry
         * @description One append-ordered transparency-log leaf.
         */
        LogEntry: {
            /** Leafindex */
            leafIndex: number;
            /** Manifestid */
            manifestId: string;
            /** Leafhash */
            leafHash: string;
        };
        /**
         * LogResponse
         * @description The ordered transparency-log leaves with the current tree head, for auditing and display.
         */
        LogResponse: {
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            /** Treesize */
            treeSize: number;
            /** Roothash */
            rootHash: string;
        };
        /**
         * Manifest
         * @description The provenance record Rooted stores and recovers.
         *
         *     system_provenance is disclosed on recovery (model, provider, timestamp). personal_provenance
         *     (prompt, user, IP) is withheld by the SB 942-style redaction layer. soft_bindings carry the
         *     watermark ID and the PDQ fingerprint used to recover this manifest when the asset is stripped.
         */
        Manifest: {
            /** Manifestid */
            manifestId: string;
            /** Assetsha256 */
            assetSha256: string;
            /** Createdat */
            createdAt: string;
            /** Systemprovenance */
            systemProvenance?: {
                [key: string]: unknown;
            };
            /** Personalprovenance */
            personalProvenance?: {
                [key: string]: unknown;
            };
            /** Softbindings */
            softBindings?: components["schemas"]["SoftBinding"][];
        };
        /**
         * Match
         * @description One SBR query result: a manifest the queried asset binds to.
         */
        Match: {
            /** Manifestid */
            manifestId: string;
            /** Similarityscore */
            similarityScore?: number | null;
            /** Endpoint */
            endpoint?: string | null;
        };
        /**
         * MerkleCheckpoint
         * @description A signed tree head, written to B2 under Object Lock for tamper-evidence.
         */
        MerkleCheckpoint: {
            /** Epoch */
            epoch: number;
            /** Treesize */
            treeSize: number;
            /** Roothash */
            rootHash: string;
            /** Signedat */
            signedAt: string;
            /** Signatureb64 */
            signatureB64: string;
        };
        /**
         * SoftBinding
         * @description A recoverable pointer from an asset to its manifest (a watermark ID or a fingerprint).
         */
        SoftBinding: {
            /** Alg */
            alg: string;
            /** Value */
            value: string;
            /**
             * Scope
             * @default all
             */
            scope: string;
        };
        /** SoftBindingQueryResult */
        SoftBindingQueryResult: {
            /** Matches */
            matches?: components["schemas"]["Match"][];
        };
        /**
         * SupportedAlgorithms
         * @description Advertised at /services/supportedAlgorithms. PDQ is deliberately absent (internal only).
         *
         *     The C2PA SBR spec shape is arrays of objects with an `alg` field, not bare strings.
         */
        SupportedAlgorithms: {
            /** Watermarks */
            watermarks?: components["schemas"]["AlgorithmEntry"][];
            /** Fingerprints */
            fingerprints?: components["schemas"]["AlgorithmEntry"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    supported_algorithms_services_supportedAlgorithms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedAlgorithms"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description manifest id already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uploaded asset too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid or unsupported image */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_by_content_matches_byContent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_matches_by_content_matches_byContent_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoftBindingQueryResult"];
                };
            };
            /** @description malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description uploaded asset too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid or unsupported image */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_by_binding_matches_byBinding_get: {
        parameters: {
            query: {
                alg: string;
                value: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoftBindingQueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            /** @description manifest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transparency_log_transparency_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"];
                };
            };
        };
    };
    transparency_checkpoint_transparency_checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointResponse"];
                };
            };
        };
    };
    transparency_proof_transparency_proof__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InclusionProofResponse"];
                };
            };
            /** @description manifest not in transparency log */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
