"""BYO direct-to-B2 upload: the presign endpoint (allowlist, size cap, degrade) and the register
endpoint (key-shape fail-closed, missing object, size cap, decode guard, the shared ingest core).
Network-free: in-memory resolver/log/storage at the same seams the webhook tests use; the presign
happy path runs the REAL boto3 signer (a purely local computation, no network)."""

from __future__ import annotations

import io
from collections.abc import Iterator
from urllib.parse import parse_qs, urlparse

import httpx
import numpy as np
import pytest
from httpx import ASGITransport
from PIL import Image

from rooted_api import byo, sbr
from rooted_api.main import app
from rooted_provenance.merkle import TransparencyLog
from rooted_provenance.resolver import InMemoryIndex, Resolver
from rooted_provenance.watermark import FakeWatermarker
from rooted_storage.storage import InMemoryStorage

_VALID_KEY = "byo/" + "ab12" * 8 + ".png"  # 32 hex chars, allowlisted extension


def _png(seed: int) -> bytes:
    rng = np.random.default_rng(seed)
    arr = (rng.random((64, 64, 3)) * 255).astype("uint8")
    buf = io.BytesIO()
    Image.fromarray(arr).save(buf, "PNG")
    return buf.getvalue()


@pytest.fixture
def storage(monkeypatch: pytest.MonkeyPatch) -> Iterator[InMemoryStorage]:
    monkeypatch.setenv("B2_BUCKET_DEV", "rooted-dev")
    sbr.set_resolver(Resolver(InMemoryIndex(), FakeWatermarker()))
    sbr.set_log(TransparencyLog())
    st = InMemoryStorage()
    sbr.set_storage(st)
    byo._REGISTERED_KEYS.clear()
    yield st
    byo._REGISTERED_KEYS.clear()
    sbr.set_resolver(None)
    sbr.set_log(None)
    sbr.set_storage(None)


@pytest.fixture
def presign_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("B2_KEY_ID", "0000key")
    monkeypatch.setenv("B2_APP_KEY", "fake-app-key")
    monkeypatch.setenv("B2_BUCKET_DEV", "rooted-dev")
    monkeypatch.setenv("B2_REGION", "us-west-004")
    monkeypatch.setenv("B2_ENDPOINT", "https://s3.us-west-004.backblazeb2.com")


def _client() -> httpx.AsyncClient:
    return httpx.AsyncClient(transport=ASGITransport(app=app), base_url="http://t")


# --- POST /demo/byo/upload-url -------------------------------------------------------------------


async def test_upload_url_rejects_disallowed_content_type(presign_env: None) -> None:
    async with _client() as c:
        r = await c.post(
            "/demo/byo/upload-url", json={"contentType": "image/gif", "sizeBytes": 1000}
        )
    assert r.status_code == 415


async def test_upload_url_rejects_svg_and_html_content_types(presign_env: None) -> None:
    # Script-capable types must never be presignable: the allowlist is the XSS/abuse gate.
    async with _client() as c:
        for ct in ("image/svg+xml", "text/html", "application/octet-stream"):
            r = await c.post("/demo/byo/upload-url", json={"contentType": ct, "sizeBytes": 10})
            assert r.status_code == 415, ct


async def test_upload_url_rejects_oversize_declaration(presign_env: None) -> None:
    async with _client() as c:
        r = await c.post(
            "/demo/byo/upload-url",
            json={"contentType": "image/png", "sizeBytes": sbr._MAX_UPLOAD_BYTES + 1},
        )
    assert r.status_code == 413


async def test_upload_url_rejects_nonpositive_size(presign_env: None) -> None:
    async with _client() as c:
        for size in (0, -1):
            r = await c.post(
                "/demo/byo/upload-url", json={"contentType": "image/png", "sizeBytes": size}
            )
            assert r.status_code == 400, size


async def test_upload_url_degrades_honestly_when_unconfigured(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    for var in ("B2_KEY_ID", "B2_APP_KEY", "B2_BUCKET_DEV", "B2_ENDPOINT", "B2_REGION"):
        monkeypatch.delenv(var, raising=False)
    async with _client() as c:
        r = await c.post(
            "/demo/byo/upload-url", json={"contentType": "image/png", "sizeBytes": 1000}
        )
    assert r.status_code == 503
    assert "not configured" in r.json()["detail"]


async def test_upload_url_happy_path_presigns_a_constrained_put(presign_env: None) -> None:
    # The real boto3 SigV4 presign runs (local computation, no network). The URL must target the
    # dev bucket, carry a server-generated byo/ key, expire in 600s, and SIGN the content type so
    # the browser PUT cannot swap it for something outside the allowlist.
    async with _client() as c:
        r = await c.post(
            "/demo/byo/upload-url", json={"contentType": "image/png", "sizeBytes": 1000}
        )
    assert r.status_code == 200, r.text
    body = r.json()
    key = body["objectKey"]
    assert key.startswith("byo/") and key.endswith(".png")
    assert len(key) == len("byo/") + 32 + len(".png")  # uuid4 hex, never a client-supplied name
    assert body["bucket"] == "rooted-dev"
    assert body["expiresInSeconds"] == 600
    assert body["maxBytes"] == sbr._MAX_UPLOAD_BYTES
    parsed = urlparse(body["uploadUrl"])
    assert parsed.scheme == "https"
    assert "backblazeb2.com" in parsed.netloc
    assert parsed.path.endswith(key)
    qs = parse_qs(parsed.query)
    assert qs["X-Amz-Expires"] == ["600"]
    assert "content-type" in qs["X-Amz-SignedHeaders"][0]
    # The presigned URL never leaks the application key (only the standard credential scope).
    assert "fake-app-key" not in body["uploadUrl"]


async def test_upload_url_keys_are_unique_per_request(presign_env: None) -> None:
    async with _client() as c:
        r1 = await c.post(
            "/demo/byo/upload-url", json={"contentType": "image/jpeg", "sizeBytes": 10}
        )
        r2 = await c.post(
            "/demo/byo/upload-url", json={"contentType": "image/jpeg", "sizeBytes": 10}
        )
    assert r1.json()["objectKey"] != r2.json()["objectKey"]
    assert r1.json()["objectKey"].endswith(".jpg")


# --- POST /demo/byo/register ---------------------------------------------------------------------


@pytest.mark.parametrize(
    "key",
    [
        "ingest/photo.png",  # wrong prefix (the event-webhook prefix, not byo/)
        "manifests/urn_c2pa_demo.json",  # a registry object, never registrable this way
        "byo/../manifests/x.json",  # traversal
        "/byo/" + "ab12" * 8 + ".png",  # absolute
        "byo/" + "ab12" * 8 + ".gif",  # extension outside the allowlist
        "byo/" + "AB12" * 8 + ".png",  # not lowercase uuid4 hex
        "byo/nested/" + "ab12" * 8 + ".png",  # nested path under the prefix
        "ab12" * 8 + ".png",  # no prefix at all
        "byo/" + "ab12" * 8 + ".png\n",  # trailing newline must not sneak past the anchor
        "byo/pretty-name.png",  # client-invented name
        "",  # empty
    ],
)
async def test_register_fails_closed_on_bad_keys(storage: InMemoryStorage, key: str) -> None:
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": key})
    assert r.status_code == 400
    assert r.json()["detail"] == "invalid object key"


async def test_register_404_when_object_missing(storage: InMemoryStorage) -> None:
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert r.status_code == 404


async def test_register_502_when_storage_download_errors(
    storage: InMemoryStorage, monkeypatch: pytest.MonkeyPatch
) -> None:
    # The object passed the size check (it exists), but the download itself fails with a storage
    # OUTAGE (not a missing object). That must surface as 502, never a dishonest 404.
    storage.put(_VALID_KEY, _png(41))

    def failing_get(key: str) -> bytes:
        raise ConnectionError("b2 unreachable")

    monkeypatch.setattr(storage, "get", failing_get)
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert r.status_code == 502


async def test_register_413_when_stored_object_oversized(
    storage: InMemoryStorage, monkeypatch: pytest.MonkeyPatch
) -> None:
    # The cap is enforced from the stored size BEFORE any download.
    storage.put(_VALID_KEY, b"small")
    monkeypatch.setattr(storage, "size", lambda key: sbr._MAX_UPLOAD_BYTES + 1)
    downloads = 0

    def counting_get(key: str) -> bytes:
        nonlocal downloads
        downloads += 1
        return b"small"

    monkeypatch.setattr(storage, "get", counting_get)
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert r.status_code == 413
    assert downloads == 0  # rejected from the stored size alone, nothing was downloaded


async def test_register_415_when_object_is_not_an_image(storage: InMemoryStorage) -> None:
    storage.put(_VALID_KEY, b"definitely not an image")
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert r.status_code == 415


async def test_register_degrades_honestly_when_storage_unconfigured(
    storage: InMemoryStorage,
) -> None:
    sbr.set_storage(None)
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert r.status_code == 503
    assert "not configured" in r.json()["detail"]


async def test_register_happy_path_makes_the_asset_recoverable(
    storage: InMemoryStorage,
) -> None:
    png = _png(21)
    storage.put(_VALID_KEY, png)
    async with _client() as c:
        r = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
        assert r.status_code == 200, r.text
        body = r.json()
        manifest_id = body["manifestId"]
        assert manifest_id.startswith("urn:c2pa:b2-")
        assert body["objectKey"] == _VALID_KEY
        assert body["bucket"] == "rooted-dev"
        assert body["backend"] == "in-memory"  # evidence-based; "backblaze-b2" only on real B2
        assert body["sizeBytes"] == len(png)
        assert body["alreadyRegistered"] is False
        assert body["recoverable"] is True

        # The loop closes: the judge's own asset now recovers by content like every other asset.
        rec = await c.post("/matches/byContent", files={"file": ("mine.png", png, "image/png")})
        assert rec.status_code == 200
        assert rec.json()["matches"][0]["manifestId"] == manifest_id

        # And it is a real transparency-log leaf with a real inclusion proof.
        proof = await c.get(f"/transparency/proof/{manifest_id}")
        assert proof.status_code == 200
        assert proof.json()["serverVerified"] is True


async def test_register_is_idempotent_for_the_same_bytes(storage: InMemoryStorage) -> None:
    png = _png(22)
    storage.put(_VALID_KEY, png)
    async with _client() as c:
        first = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
        second = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert first.json()["alreadyRegistered"] is False
    assert second.json()["alreadyRegistered"] is True
    assert second.json()["manifestId"] == first.json()["manifestId"]


async def test_register_rerun_answers_without_download_or_decode(
    storage: InMemoryStorage, monkeypatch: pytest.MonkeyPatch
) -> None:
    # The idempotency short-circuit: once a key is registered, re-registering it must not fetch or
    # decode the object again (a caller looping register on one valid key gains no amplification).
    png = _png(23)
    storage.put(_VALID_KEY, png)
    async with _client() as c:
        first = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
        assert first.status_code == 200

        downloads = 0

        def counting_get(key: str) -> bytes:
            nonlocal downloads
            downloads += 1
            return png

        monkeypatch.setattr(storage, "get", counting_get)
        second = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert second.status_code == 200
    assert second.json()["alreadyRegistered"] is True
    assert second.json()["manifestId"] == first.json()["manifestId"]
    assert second.json()["sizeBytes"] == len(png)
    assert downloads == 0  # answered from the bounded key cache after only a size check


async def test_register_cache_falls_through_when_stored_size_changes(
    storage: InMemoryStorage,
) -> None:
    # A key re-PUT with different bytes inside the presign window must not get a stale answer:
    # the size mismatch falls through to the full download-and-ingest path.
    first_png = _png(24)
    storage.put(_VALID_KEY, first_png)
    async with _client() as c:
        first = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
        assert first.status_code == 200
        # A different image DIMENSION guarantees a different byte size (two random 64x64 PNGs can
        # coincidentally compress to identical lengths).
        rng = np.random.default_rng(25)
        arr = (rng.random((80, 80, 3)) * 255).astype("uint8")
        buf = io.BytesIO()
        Image.fromarray(arr).save(buf, "PNG")
        second_png = buf.getvalue()
        assert len(second_png) != len(first_png)
        storage.put(_VALID_KEY, second_png)
        second = await c.post("/demo/byo/register", json={"objectKey": _VALID_KEY})
    assert second.status_code == 200
    assert second.json()["manifestId"] != first.json()["manifestId"]
    assert second.json()["alreadyRegistered"] is False
