"use client";

import { useState } from "react";
import { AnimatePresence } from "motion/react";

import { $api } from "@/lib/api/client";
import { Row, Slot } from "@/components/recover-panel";

// The headline interactive beat: a visitor types a prompt, the backend generates a real AI image and
// registers it (sign + watermark + fingerprint + log), the UI shows the credentialed asset, then the
// visitor STRIPS it in-browser (a canvas JPEG re-encode that destroys any embedded credential) and
// RECOVERS it back to a green VERIFIED state. Every visible state is driven by a real fetch result:
// the generate response, the /matches/byContent result, and the recovered manifest query. When the
// backend tells us it fell back to the seeded asset, we say so (an honest amber note), so a seeded
// asset is never mistaken for a fresh generation.

type GenManifest = {
  manifestId: string;
  assetSha256: string;
  createdAt: string;
  systemProvenance: { model?: string; provider?: string; generator?: string; [k: string]: unknown };
  softBindings?: { alg: string; value: string }[];
};

type GenerateResponse = {
  image: string;
  manifestId: string;
  watermarkId: string;
  merkleIndex: number;
  model: string;
  provider: string;
  signatureB64: string;
  manifest: GenManifest;
  storedOnB2: boolean;
  fellBackToSeed: boolean;
  reason: string | null;
};

function truncate(s: string, head = 28): string {
  return s.length > head ? `${s.slice(0, head)}…` : s;
}

// Decode a data URL ("data:image/...;base64,....") to a Blob without a network round-trip. This is
// both the source the canvas re-encodes and the fallback when a real canvas is unavailable.
function dataUrlToBlob(dataUrl: string): Blob {
  const comma = dataUrl.indexOf(",");
  const head = dataUrl.slice(0, comma);
  const body = dataUrl.slice(comma + 1);
  const mime = /data:([^;]+)/.exec(head)?.[1] ?? "image/jpeg";
  const bytes = /;base64/i.test(head) ? atob(body) : decodeURIComponent(body);
  const arr = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i += 1) arr[i] = bytes.charCodeAt(i);
  return new Blob([arr], { type: mime });
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("image decode failed"));
    img.src = src;
  });
}

// The strip: draw the generated image onto a canvas and export it as a fresh JPEG Blob. A re-encode
// like this is exactly what a screenshot or a re-upload does, it destroys any embedded credential.
// jsdom (the test environment) has no real 2D canvas: getContext throws or returns null, so we fall
// back to the original generated bytes and the recovery loop still closes deterministically.
async function stripToBlob(dataUrl: string): Promise<Blob> {
  const original = dataUrlToBlob(dataUrl);

  let canvas: HTMLCanvasElement | null = null;
  let ctx: CanvasRenderingContext2D | null = null;
  try {
    canvas = document.createElement("canvas");
    ctx = canvas.getContext("2d");
  } catch {
    ctx = null;
  }
  if (!canvas || !ctx || typeof canvas.toBlob !== "function") return original;

  try {
    const img = await loadImage(dataUrl);
    canvas.width = img.naturalWidth || img.width || 1;
    canvas.height = img.naturalHeight || img.height || 1;
    ctx.drawImage(img, 0, 0);
    const reencoded = await new Promise<Blob | null>((resolve) => {
      canvas!.toBlob((b) => resolve(b), "image/jpeg", 0.9);
    });
    return reencoded ?? original;
  } catch {
    return original;
  }
}

export function GeneratePanel() {
  const [prompt, setPrompt] = useState("");
  const [gen, setGen] = useState<GenerateResponse | null>(null);
  const [genPending, setGenPending] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);
  const [recoveredId, setRecoveredId] = useState<string | null>(null);
  const [score, setScore] = useState<number | null>(null);

  const recover = $api.useMutation("post", "/matches/byContent");
  const manifest = $api.useQuery(
    "get",
    "/manifests/{manifest_id}",
    { params: { path: { manifest_id: recoveredId ?? "" } } },
    { enabled: recoveredId != null },
  );

  async function generate() {
    const trimmed = prompt.trim();
    if (trimmed === "" || genPending) return;
    setGenPending(true);
    setGenError(null);
    setGen(null);
    setRecoveredId(null);
    setScore(null);
    recover.reset();
    try {
      const res = await fetch("/api/demo/generate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ prompt: trimmed }),
      });
      if (!res.ok) {
        const detail = await res
          .json()
          .then((d: { detail?: string }) => d.detail)
          .catch(() => null);
        setGenError(detail ?? `The generator is unavailable (HTTP ${res.status}).`);
        return;
      }
      const data: GenerateResponse = await res.json();
      setGen(data);
    } catch {
      setGenError("Backend unreachable. Start it with uv run fastapi dev api/main.py.");
    } finally {
      setGenPending(false);
    }
  }

  function stripAndRecover() {
    if (!gen) return;
    setRecoveredId(null);
    setScore(null);
    void stripToBlob(gen.image).then((blob) => {
      recover.mutate(
        {
          // The schema types the multipart `file` field as string; we send the real Blob and let the
          // FormData serializer carry it (when bodySerializer returns FormData, fetch sets the boundary).
          body: { file: blob as unknown as string },
          bodySerializer: (b) => {
            const fd = new FormData();
            fd.append("file", b.file as unknown as Blob, "stripped.jpg");
            return fd;
          },
        },
        {
          onSuccess: (data) => {
            const match = data.matches?.[0];
            if (match) {
              setRecoveredId(match.manifestId);
              setScore(match.similarityScore ?? null);
            }
          },
        },
      );
    });
  }

  const matched = recover.isSuccess && (recover.data.matches?.length ?? 0) > 0;
  const noMatch = recover.isSuccess && (recover.data.matches?.length ?? 0) === 0;

  return (
    <section className="rounded-xl border border-white/15 bg-white/[0.04] p-6 backdrop-blur-md">
      <h2 className="mb-1 text-xs uppercase tracking-widest text-white/50">Live loop</h2>
      <p className="mb-4 text-[11px] text-white/55">
        Type a prompt. We generate a real image, sign and log it, then you strip it and watch Rooted
        recover it.
      </p>

      <div className="flex flex-col gap-3 sm:flex-row sm:items-end">
        <label className="flex-1 font-mono text-xs text-white/60">
          prompt
          <textarea
            value={prompt}
            maxLength={500}
            rows={2}
            placeholder="a lighthouse on a cliff at dusk"
            onChange={(e) => setPrompt(e.target.value)}
            className="mt-1 w-full resize-none rounded border border-white/15 bg-black/40 px-2 py-1 text-white/90 placeholder:text-white/55"
          />
        </label>
        <button
          type="button"
          onClick={generate}
          disabled={prompt.trim() === "" || genPending}
          className="shrink-0 rounded border border-white/20 px-4 py-2 font-mono text-xs text-white/80 transition hover:border-white/40 hover:bg-white/[0.03] disabled:cursor-not-allowed disabled:opacity-40"
        >
          {genPending ? "Generating…" : "Generate"}
        </button>
      </div>

      <div className="mt-5 min-h-24">
        <AnimatePresence mode="wait">
          {!gen && !genPending && genError == null && (
            <Slot key="idle" className="text-white/55">
              Awaiting a prompt.
            </Slot>
          )}

          {!gen && genPending && (
            <Slot key="generating" className="text-sky-300">
              <span className="inline-flex items-center gap-2">
                <span className="h-2 w-2 animate-ping rounded-full bg-sky-300" />
                Generating, signing, and logging the asset…
              </span>
            </Slot>
          )}

          {!gen && genError != null && (
            <Slot key="gen-error" className="text-amber-400">
              <p className="text-sm">{genError}</p>
              <p className="mt-1 text-xs text-white/55">
                You can still recover the seeded demo asset in the panel below.
              </p>
            </Slot>
          )}

          {gen && (
            <Slot key="generated" className="text-white/70">
              {gen.fellBackToSeed && (
                <p className="mb-3 rounded border border-amber-400/30 bg-amber-400/[0.06] px-3 py-2 text-xs text-amber-300">
                  Showing the seeded demo asset: {gen.reason ?? "the live generator was unavailable."}
                </p>
              )}

              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={gen.image}
                alt="Generated, credentialed asset"
                className="mb-3 w-full max-w-xs rounded-lg border border-white/10"
              />

              <dl className="grid gap-1 font-mono text-xs text-white/70">
                <p className="mb-1 text-[11px] uppercase tracking-widest text-emerald-300/80">
                  Registered
                </p>
                <Row k="manifest" v={truncate(gen.manifestId)} />
                <Row k="model" v={`${gen.model} (${gen.provider})`} />
                <Row k="watermark" v={gen.watermarkId} />
                <Row k="transparency" v={`leaf #${gen.merkleIndex}`} />
                <Row k="state" v={gen.storedOnB2 ? "signed + logged + stored on B2" : "signed + logged"} />
              </dl>

              {recover.isIdle && (
                <button
                  type="button"
                  onClick={stripAndRecover}
                  className="mt-4 rounded border border-white/20 px-4 py-2 font-mono text-xs text-white/80 transition hover:border-white/40 hover:bg-white/[0.03]"
                >
                  Strip and recover
                </button>
              )}

              {recover.isPending && (
                <p className="mt-4 inline-flex items-center gap-2 font-mono text-xs text-sky-300">
                  <span className="h-2 w-2 animate-ping rounded-full bg-sky-300" />
                  Stripped. Scanning watermark and perceptual hash…
                </p>
              )}

              {recover.isError && (
                <p className="mt-4 font-mono text-xs text-amber-400">
                  Recovery request failed. The backend may be unreachable.
                </p>
              )}

              {noMatch && (
                <div className="mt-4 text-rose-400">
                  <p className="text-lg font-semibold">FAILED</p>
                  <p className="text-sm text-white/50">
                    No provenance recovered for the stripped asset.
                  </p>
                </div>
              )}

              {matched && (
                <div className="mt-4 text-emerald-300">
                  <p className="text-lg font-semibold">VERIFIED</p>
                  <dl className="mt-2 grid gap-1 font-mono text-xs text-white/70">
                    <Row k="manifest" v={recoveredId ?? "…"} />
                    {score != null && <Row k="similarity" v={`${score}/100 (fingerprint)`} />}
                    {manifest.data && (
                      <>
                        <Row k="created" v={manifest.data.createdAt} />
                        <Row k="system" v={JSON.stringify(manifest.data.systemProvenance)} />
                        {manifest.data.softBindings?.map((b) => (
                          <Row key={b.alg} k={b.alg} v={b.value} />
                        ))}
                      </>
                    )}
                  </dl>
                  <p className="mt-2 text-xs text-white/55">Provenance proves origin, not truth.</p>
                </div>
              )}
            </Slot>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}
